### ISSUE TITLE
Model size info

### ISSUE THREAD

**Issue by cvampal** [Zhendong-Wang/Patch-Diffusion#10]
Can you please share the number of trainable parameters for each model (CelebA, ImageNet, LSUN-Bedroom, and LSUN-Church)?

**Comment by Zhendong-Wang** [comment]
The number of trainable parameters are very similar to those of the original EDM model, since we majorly modify the first conv layer. You could call `print('Number of  Parameters: {sum(p.numel() for p in model.parameters()):,}")` this easily to get the model size.
